
---

- name: Set configured port fact
  set_fact:
    configured_port: "{{ ansible_port }}"

- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ configured_port }}"
  notify: "Restart sshd"

- name: Setup selinux for alternate SSH port
  seport:
    ports: "{{ configured_port }}"
    proto: "tcp"
    setype: "ssh_port_t"
    state: "present"

  - name: Restart sshd
      service:
        name: sshd
        state: restarted
